export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const UPLOAD_IMAGE_RESET = "UPLOAD_IMAGE_RESET";

export const INSTRUCTOR_REGISTER_REQUEST = "INSTRUCTOR_REGISTER_REQUEST";
export const INSTRUCTOR_REGISTER_SUCCESS = "INSTRUCTOR_REGISTER_SUCCESS";
export const INSTRUCTOR_REGISTER_FAIL = "INSTRUCTOR_REGISTER_FAIL";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";
