/** @format */

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL";

export const COURSE_GET_REQUEST = "COURSE_GET_REQUEST";
export const COURSE_GET_SUCCESS = "COURSE_GET_SUCCESS";
export const COURSE_GET_FAIL = "COURSE_GET_FAIL";

export const COURSE_ADD_LESSON_REQUEST = "COURSE_ADD_LESSON_REQUEST";
export const COURSE_ADD_LESSON_SUCCESS = "COURSE_ADD_LESSON_SUCCESS";
export const COURSE_ADD_LESSON_FAIL = "COURSE_ADD_LESSON_FAIL";
